# SPDX-FileCopyrightText: 2024 Andrew Pantuso <ajpantuso@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0

[tools]
go = "1.22"
pre-commit = "latest"
"pipx:reuse" = "latest"

[tasks.run]
run="go run main.go"

[tasks.fmt]
run="find $(git rev-parse --show-toplevel) -name '*.go' -exec gofmt -s -w {} +"

[tasks.tidy]
run="go mod tidy"

[tasks.test]
run="go test -v ./..."
